service: justread-api
useDotenv: true

custom:
  serverless-offline:
    noPrependStageInUrl: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-northeast-2
  stackName: justread-api
  apiName: justread-api
  memorySize: 128
  timeout: 5
  deploymentBucket:
    name: best.justread.api.${self:provider.region}.deploys
    maxPreviousDeploymentArtifacts: 5 # On every deployment the framework prunes the bucket to remove artifacts older than this limit. The default is 5
  environment:
    TZ: Asia/Seoul

functions:
  app:
    handler: build/serverless.handler
    description: JustRead REST API
    events:
      - http:
          path: /
          method: any
          cors: true
      - http:
          path: /{any+}
          method: any
          cors: true
